body:
  - type: textarea
    id: question
    attributes:
      label: Describe your question
      description: Please describe your question as clearly and concisely as possible.
    validations:
      required: true

  - type: dropdown
    id: hosting
    attributes:
      label: Are you using Langfuse Cloud or self-hosting?
      options:
        - Langfuse Cloud
        - Self-hosted Langfuse
    validations:
      required: true
 - type: checkboxes
    attributes:
      label: Check that box!
      options:
        - label: This one!
          required: true
        - label: I won't stop you if you check this one, too
