# (top-level keys like `name:` and `description:` omitted for brevity)

body:
  - type: textarea
    id: question
    attributes:
      label: Describe your question
      description: Please describe your question as clearly and concisely as possible.
    validations:
      required: true
