body:
  - type: textarea
    id: question
    attributes:
      label: Describe your question
      description: Please describe your question as clearly and concisely as possible.
    validations:
      required: true

  - type: dropdown
    id: hosting
    attributes:
      label: Are you using Langfuse Cloud or self-hosting?
      options:
        - Langfuse Cloud
        - Self-hosted Langfuse
    validations:
      required: true

  - type: checkboxes
    id: confirmations
    attributes:
      label: Before submitting
      description: |
        Please confirm you've done the following:
        - Checked for an existing [issue](https://github.com/langfuse/langfuse/issues)
        - Searched existing [discussions](https://github.com/orgs/langfuse/discussions)
        - Asked the [Langfuse AI](https://langfuse.com/docs/ask-ai) for help
      options:
        - I checked existing issues.
        - I searched existing discussions.
        - I asked the Langfuse AI for help.
    validations:
      required: true
